quarkus:
  application:
    name: Inventory CLI
  container-image:
    group: romulomf
    name: inventory-cli
    registry: quay.io
  grpc:
    clients:
      inventory:
        host: localhost
        port: 9000