quarkus:
  application:
    name: Reservation Service
  container-image:
    group: romulomf
    name: reservation-service
    registry: quay.io
  datasource:
    db-kind: postgresql
    username: user
    password: pass
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
  http:
    port: 8081
    test-port: 8181
  oidc:
    application-type: service
    auth-server-url: http://localhost:7777/realms/car-rental
    client-id: reservation-service
    token-state-manager:
      split-tokens: true
  rest-client:
    rental:
      url: http://localhost:8082
  smallrye-graphql-client:
    inventory:
      url: http://localhost:8083/graphql
"%test":
  mp:
    messaging:
      incoming:
        invoices-rabbitmq:
          connector: smallrye-rabbitmq
          queue:
            name: invoices
          exchange:
            name: invoices
"%prod":
  quarkus:
    datasource:
      reactive:
        url: vertx-reactive:postgresql://localhost:5432/reservation
    oidc:
      auth-server-url: http://localhost:7777/realms/car-rental
      client-id: reservation-service
      token-state-manager:
        split-tokens: true
  rabbitmq-host: localhost
  rabbitmq-port: 5672
  rabbitmq-http-port: 15672
  rabbitmq-username: guest
  rabbitmq-password: guest