quarkus:
  application:
    name: Reservation Service
  datasource:
    db-kind: postgresql
    username: user
    password: pass
    devservices:
      port: 5432
  hibernate-orm:
    database:
      generation: drop-and-create
  http:
    port: 8081
    test-port: 8181
  oidc:
    application-type: service
    devservices:
      enabled: true
  smallrye-graphql-client:
    inventory:
      url: http://localhost:8083/graphql
"%prod":
  quarkus:
    datasource:
      reactive:
        url: vertx-reactive:postgresql://localhost:5432/reservation