quarkus:
  application:
    name: Inventory Service
  container-image:
    builder: openshift
    group: romulomf
    name: inventory-service
    registry: quay.io
  datasource:
    db-kind: mysql
    username: user
    password: pass
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
    sql-load-script: import.sql
  http:
    port: 8083
  kubernetes:
    env:
      vars:
        quarkus-datasource-jdbc-url: jdbc:mysql://mysql:3306/inventory
    name: inventory-service
    namespace: default
    prometheus:
      generate-service-monitor: false
    route:
      expose: true
  smallrye-graphql:
    ui:
      always-include: true
"%prod":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:mysql://localhost:3306/inventory